version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: geo-postgres
    environment:
      POSTGRES_DB: geo_db
      POSTGRES_USER: geo_user
      POSTGRES_PASSWORD: geo_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: geo-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
