spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/geo_db
    username: geo_user
    password: geo_pass
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
  kafka:
    bootstrap-servers: localhost:9092

aws:
  s3:
    bucket: geo-files

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"